# X11 DPI / toolkit scaling generated for dwm sessions.
{ lib, hostSettings, ... }:

let
  metal = {
    dpi = hostSettings.dpi or 96;
    scale = hostSettings.scale or 1;
  };
  vm = {
    dpi = 96;
    scale = 1;
  };
  mkXsettingsd = p: ''
    Xft/DPI ${toString (p.dpi * 1024)}
    Xft/Antialias 1
    Xft/Hinting 1
    Xft/HintStyle "hintfull"
    Xft/RGBA "rgb"
    Gdk/WindowScalingFactor ${toString p.scale}
    Gdk/UnscaledDPI ${toString (p.dpi / p.scale * 1024)}
  '';
in
{
  config = lib.mkIf ((hostSettings.desktop or "none") == "dwm") {
    xdg.configFile = {
      "xsettingsd/xsettingsd-metal.conf".text = mkXsettingsd metal;
      "xsettingsd/xsettingsd-vm.conf".text = mkXsettingsd vm;
      "graphics/profile.sh".text = ''
        # Generated by home/apps/graphics/default.nix -- do not edit by hand.
        if systemd-detect-virt -q; then
          GFX_DPI=${toString vm.dpi}
          GFX_SCALE=${toString vm.scale}
          GFX_XSETTINGSD="$HOME/.config/xsettingsd/xsettingsd-vm.conf"
        else
          GFX_DPI=${toString metal.dpi}
          GFX_SCALE=${toString metal.scale}
          GFX_XSETTINGSD="$HOME/.config/xsettingsd/xsettingsd-metal.conf"
        fi
      '';
    };
  };
}
