# Session environment: the single source of truth for user environment
# variables and PATH. One attrset drives BOTH delivery channels:
#   (1) home.sessionVariables / home.sessionPath -> hm-session-vars.sh, sourced
#       by the Home-Manager-generated ~/.profile and ~/.bashrc (login shells
#       incl. TTY/SSH, and interactive shells).
#   (2) a GENERATED ~/.config/environment.d/10-session.conf, rendered from the
#       same merged set -> the systemd-user / graphical session, which does not
#       read hm-session-vars.sh on the non-NixOS standalone-HM hosts.
# No static environment.d assets, no hand-written profile.sh bridge.
{ lib, config, ... }:

let
  # PATH prepends authored once; fed to home.sessionPath (shells) and to the
  # generated environment.d PATH line (systemd-user / graphical).
  sessionPathPrepends = [
    "$HOME/.cache/.bun/bin"
    "$HOME/.bun/bin"
    "$HOME/.local/bin"
    "$HOME/.local/share/bebash/commands"
    "$HOME/.cargo/bin"
  ];

  # Render environment.d(5) lines from the fully-merged sessionVariables (this
  # module's, plus whatever a consumer adds -- e.g. EXOBRAIN_* in nix-secrets).
  # Reading config.home.sessionVariables while writing xdg.configFile is a
  # normal module fixpoint: the generated file is never fed back into
  # sessionVariables, so there is no recursion. Sorted for reproducible output.
  envVars = lib.filterAttrs (_: v: v != null) config.home.sessionVariables;
  header = "# Generated by home-manager (modules/home/env-shell.nix) from\n# home.sessionVariables + home.sessionPath. Do not edit by hand.";
  envdLines = builtins.sort (a: b: a < b) (
    lib.mapAttrsToList (n: v: "${n}=${toString v}") envVars
    ++ [ "PATH=${lib.concatStringsSep ":" sessionPathPrepends}:\${PATH}" ]
  );
in
{
  # SoT. Cross-variable references are resolved at Nix eval time (absolute
  # paths) because hm-session-vars.sh writes these in an unspecified order, so
  # no value may depend on another at runtime. ${XDG_RUNTIME_DIR} / ${HOME} are
  # kept as genuine per-session runtime expansions.
  home.sessionVariables = {
    EDITOR = "nvim";
    VISUAL = "nvim";
    SUDO_EDITOR = "nvim";
    SYSTEMD_EDITOR = "nvim";
    PROJECTS = "${config.home.homeDirectory}/Projects";
    XCURSOR_THEME = "Bibata-Modern-Classic";
    XCURSOR_SIZE = "32";
    SSH_AUTH_SOCK = "\${XDG_RUNTIME_DIR}/ssh-agent.socket";
    SSH_ASKPASS = "\${HOME}/.local/bin/ssh-askpass-rofi";
    SSH_ASKPASS_REQUIRE = "prefer";
  };

  home.sessionPath = sessionPathPrepends;

  # Generated feed for the systemd-user / graphical session. A single fragment;
  # the 10- prefix sorts it ahead of anything a consumer might add.
  xdg.configFile."environment.d/10-session.conf".text =
    lib.concatStringsSep "\n" ([ header ] ++ envdLines) + "\n";
}
