# X11 DPI / toolkit scaling — single source of truth, parametrized per context.
#
# The whole desktop keys on ONE value per context: the display DPI (and an
# integer scale). `Xft.dpi` is the single source of truth applied at session
# start (see session/xinitrc); GTK derives from the generated xsettingsd config,
# Qt from QT_SCALE_FACTOR, and rofi inherits via `dpi: 0`.
#
# Why a runtime split instead of pure Nix: `virtualisation.vmVariant` overrides
# only the SYSTEM config, never Home Manager, so a host's metal build and its
# throwaway VM share this exact HM output. The metal-vs-VM choice therefore
# cannot be known at build time — xinitrc resolves it at runtime with
# `systemd-detect-virt`. This module bakes BOTH the per-host metal profile and
# the shared VM profile; xinitrc picks one.
#
# The per-host metal profile comes from `hostSettings` (threaded via
# home-manager.extraSpecialArgs in lib/mk-host.nix): a consumer sets
# `hostSettings = { dpi = 192; scale = 2; }` per host. The VM profile is fixed.
{ hostSettings, ... }:

let
  # Per-host metal profile from the consumer; sensible 1x/96 fallback.
  metal = {
    dpi = hostSettings.dpi or 96;
    scale = hostSettings.scale or 1;
  };

  # Shared VM profile: matches the 1600x900 QEMU display (modules/vm.nix).
  vm = {
    dpi = 96;
    scale = 1;
  };

  # XSETTINGS encodes Xft/DPI and Gdk/UnscaledDPI as (DPI * 1024). UnscaledDPI
  # is the pre-scale font DPI, so it is DPI/scale (e.g. 192/2 = 96) to avoid
  # double-scaling on HiDPI. Scales are integer, so the division is exact.
  mkXsettingsd = p: ''
    Xft/DPI ${toString (p.dpi * 1024)}
    Xft/Antialias 1
    Xft/Hinting 1
    Xft/HintStyle "hintfull"
    Xft/RGBA "rgb"
    Gdk/WindowScalingFactor ${toString p.scale}
    Gdk/UnscaledDPI ${toString (p.dpi / p.scale * 1024)}
  '';
in
{
  xdg.configFile."xsettingsd/xsettingsd-metal.conf".text = mkXsettingsd metal;
  xdg.configFile."xsettingsd/xsettingsd-vm.conf".text = mkXsettingsd vm;

  # Sourced by ~/.xinitrc before any GUI daemon/app starts. Picks the VM vs
  # metal profile at runtime (see module header for why this is a runtime call).
  xdg.configFile."graphics/profile.sh".text = ''
    # Generated by modules/home/graphics.nix -- do not edit by hand.
    # Sets GFX_DPI / GFX_SCALE / GFX_XSETTINGSD for the current context.
    if systemd-detect-virt -q; then
      GFX_DPI=${toString vm.dpi}
      GFX_SCALE=${toString vm.scale}
      GFX_XSETTINGSD="$HOME/.config/xsettingsd/xsettingsd-vm.conf"
    else
      GFX_DPI=${toString metal.dpi}
      GFX_SCALE=${toString metal.scale}
      GFX_XSETTINGSD="$HOME/.config/xsettingsd/xsettingsd-metal.conf"
    fi
  '';
}
