auto_commit: true
defaults:
  board: default
  status: backlog
  priority: medium
  template: task
projects: []
boards:
- name: default
  statuses:
  - backlog
  - todo
  - in-progress
  - review
  - done
ui:
  opener: nvim -R
  tree_depth: 2
  fzf_opts: --border
ai:
  enabled: false
sync:
  conflict_detection: true
